src/Controller/CatchAllController.php, src/EventListener/JsonRequestBodyValidationSubscriber.php, src/EventListener/JsonResponseExceptionSubscriber.php, src/Exception/BadJsonRequestHttpException.php, src/Exception/HttpExceptionInterface.php, src/Exception/InvalidRequestHttpException.php, src/Resources/config/services.xml, src/Routing/RouteLoader.php, tests/Controller/CatchAllControllerTest.php, tests/EventListener/JsonRequestBodyValidationSubscriberTest.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php
This PR includes:
* Improved differentiation between types of errors within the `JsonRequestBodyValidationSubscriber`.
* A controller to catch all requests to paths with unavailable routes to both be able to improve error messages and triggering the Symfony's security access control on all API paths.
* An exception subscriber to transform exception to readable JSON responses. With implementation to display additional information for the `BadJsonRequestHttpException` and `InvalidRequestHttpException`.
Closes #10.
=> Add transformation of exceptions to JSON responses

composer.lock
Fixes the following issue:
> IssueId: 32643030
> Message: There is a security advisory for your installed version of symfony/http-foundation:[CVE-2018-14773: Remove support for legacy and risky HTTP headers](https://symfony.com/blog/cve-2018-14773-remove-support-for-legacy-and-risky-http-headers)
> Filename: composer.lock
> LineNumber: 972
> Link: https://scrutinizer-ci.com/g/nijens/openapi-bundle/issues/master/files/composer.lock?orderField=path&order=asc&honorSelectedPaths=0&issueId=32643030
It doesn't have any effect on projects using this bundle. Though, it's always nice to have a bundle without Scrutinizer errors. 😃
=> Update dependencies in lockfile

README.md, composer.json, composer.lock, src/EventListener/JsonRequestBodyValidationSubscriber.php, src/EventListener/JsonResponseExceptionSubscriber.php, src/Exception/BadJsonRequestHttpException.php, src/Resources/config/services.xml, src/Service/ExceptionJsonResponseBuilder.php, src/Service/ExceptionJsonResponseBuilderInterface.php, tests/DependencyInjection/NijensOpenapiExtensionTest.php, tests/EventListener/JsonRequestBodyValidationSubscriberTest.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php, tests/Service/ExceptionJsonResponseBuilderTest.php
The default error response template looks like:
```json
{
"message": "Validation of JSON request body failed.",
"errors": [
"The property iAmRequired is required",
"The property iAmExtra is not defined and the definition does not allow additional properties"
]
}
```
If your project requires a different formatting of the response or perhaps different response codes, the default response builder can be overridden. Following the ["How to Decorate Services" guide from Symfony](https://symfony.com/doc/current/service_container/service_decoration.html), you can define your own service which implements `JsonResponseBuilderExceptionInterface` and handles the error response building instead of `nijens_openapi.service.json_response_builder_exception`. When validation against the schema fails, an …
=> Add capability to override exception responses

src/Json/SchemaLoader.php, src/Json/SchemaLoaderInterface.php, src/Routing/RouteLoader.php, tests/Json/SchemaLoaderTest.php
When an OpenAPI specification file loaded by the `RouteLoader` is changed the routes aren't reloaded into the container cache.
This happens only during development of your project, but could be a productivity killer when making changes to the specification and having to clear the cache manually on every change.
This PR adds the OpenAPI specification file as `FileResource` to the `RouteCollection`. This way, the router should be able to detect the freshness of the routing cache and reload it when the specification file is changed.
=> RouteLoader resource change detection

README.md, composer.json, composer.lock, src/Json/SchemaLoader.php, tests/Resources/specifications/route-loader-minimal.txt, tests/Resources/specifications/route-loader-minimal.yaml, tests/Resources/specifications/route-loader-minimal.yml, tests/Routing/RouteLoaderTest.php
Allow for the spec file referenced in the route definition to be `.json`, `.yaml`, or `.yml`
=> Add YAML spec handling

src/EventListener/JsonResponseExceptionSubscriber.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php
This PR changes the listening priority of `JsonResponseExceptionSubscriber` to be able to catch firewall exceptions.
The `ExceptionJsonResponseBuilder` does not yet provide a correct JSON response for the `AuthenticationException` and `AccessDeniedException`. This will be improved in a following PR.
=> Change priority of listening for kernel.exception events in JsonResponseExceptionSubscriber

src/EventListener/JsonRequestBodyValidationSubscriber.php, src/EventListener/JsonResponseExceptionSubscriber.php, src/Resources/config/services.xml, src/Routing/RouteLoader.php, tests/DependencyInjection/NijensOpenapiExtensionTest.php, tests/EventListener/JsonRequestBodyValidationSubscriberTest.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php, tests/Routing/RouteLoaderTest.php
`$router->getRouteCollection()` can become quite slow with more complicated routers. This moves the configuration needed to validate the request from the route's options to its defaults. This means that they are accessible in the request parameters.
Fixes #19
=> Remove routecollection

.travis.yml, composer.lock
This PR updates Travis CI to use a supported PHP version and also test the bundle with the Symfony version 4.1, 4.3 and 4.4 components.
=> Update Continuous Integration

src/Json/Schema/Constraint/TypeConstraint.php, src/Resources/config/services.xml, tests/Json/Schema/Constraint/TypeConstraintTest.php
This PR add support for successful validation of `null` when the `nullable` property is set to `true`.
With this change the following schema, within an OpenAPI specification, will successfully validate both `string` and `null` values:
```json
{
"type": "string",
"nullable": true
}
```
=> Add support for nullable validation

src/EventListener/JsonResponseExceptionSubscriber.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php
This PR reverts the changes made in the priority of JsonResponseExceptionSubscriber to its former value because no correct JSON response exists for the AuthenticationException and AccessDeniedException.
=> Reverted priority change of listening to kernel.exception events in JsonResponseExceptionSubscriber

src/Json/SchemaLoader.php, src/Resources/config/services.xml, src/Routing/RouteLoader.php, tests/Json/SchemaLoaderTest.php, tests/Routing/RouteLoaderTest.php
This PR changes the `RouteLoader` extend from `Loader` to `FileLoader`.
By changing the `RouteLoader` to a `FileLoader` it implements the `FileLocator` and removes the need for the `FileLocator` inside the `SchemaLoader`.
Effectively solving the `Loading the file "openapi.yaml" from the global resource directory` deprecation warning for Symfony 5.x and still be compatible with Symfony 3.4.
Relates to: #23
=> Change RouteLoader to a FileLoader

.travis.yml, composer.json, composer.lock, src/EventListener/JsonRequestBodyValidationSubscriber.php, src/EventListener/JsonResponseExceptionSubscriber.php, tests/EventListener/JsonRequestBodyValidationSubscriberTest.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php
This pull request adds full symfony 5 support. Do note, this pull request does not have symfony 3.4 or symfony 4.x support anymore.
#23
=> Symfony 5.x support

.travis.yml, src/EventListener/JsonRequestBodyValidationSubscriber.php, tests/EventListener/JsonRequestBodyValidationSubscriberTest.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php
This PR adds testing of PHP 7.4 and 8.0 to the Travis CI build matrix.
=> Add testing of PHP 7.4 and 8.0 to the Travis CI build matrix

README.md
This PR adds the long awaited documentation about the default validation error responses that come with the bundle.
Closes #21.
=> Add documentation of the default validation error responses to README

.gitattributes
This PR fixes the missing files in the release archive of version [1.0.0](https://github.com/nijens/openapi-bundle/releases/tag/1.0.0).
Fixes #43.
=> Fix missing files in version archives

.github/bin/parse-coverage, .github/workflows/continuous-integration.yaml, CONTRIBUTING.md, Makefile
This PR adds the Continuous Integration as GitHub Actions workflow. This will eventually replace the current Travis CI builds.
Until the workflow is merged, the build output can be seen [here](https://github.com/niels-nijens/openapi-bundle/actions?query=workflow%3A%22Continuous+Integration%22+branch%3Agithub-actions).
=> Add GitHub Actions CI workflow

.github/workflows/continuous-integration.yaml, Makefile, README.md, composer.json, composer.lock, src/EventListener/JsonResponseExceptionSubscriber.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php, tests/Functional/App/Controller/ErrorController.php, tests/Functional/App/Kernel.php, tests/Functional/App/config.yaml, tests/Functional/App/openapi.yaml, tests/Functional/ErrorResponsesTest.php
This PR will:
* Remove support for PHP 7.1 and Symfony 3.4.
* Add testing for Symfony 5.3
* The fix from #45 with functional tests
=> Remove PHP 7.1 and Symfony 3.4 support

composer.json, composer.lock, src/EventListener/JsonRequestBodyValidationSubscriber.php, src/EventListener/JsonResponseExceptionSubscriber.php, src/Resources/config/services.xml, src/Routing/RouteContext.php, src/Routing/RouteLoader.php, src/Serialization/SerializationContextBuilder.php, src/Serialization/SerializationContextBuilderInterface.php, tests/EventListener/JsonRequestBodyValidationSubscriberTest.php, tests/EventListener/JsonResponseExceptionSubscriberTest.php, tests/Functional/App/Controller/GetPetController.php, tests/Functional/App/Model/Pet.php, tests/Functional/App/config.yaml, tests/Functional/App/openapi.yaml, tests/Functional/SerializationTest.php, tests/Json/SchemaLoaderMock.php, tests/Routing/RouteLoaderTest.php, tests/Serialization/SerializationContextBuilderTest.php
This PR adds a `SerializationContextBuilder` service which allows you to provide the Symfony Serializer with a serialization context based on your OpenAPI specification.
```php
class ExampleController
{
public function __invoke(
Request $request, 
SerializerInterface $serializer, 
SerializationContextBuilder $serializationContextBuilder
): JsonResponse {
$serializationContext = $serializationContextBuilder->getContextForSchemaObject(
'Pet',
$request->attributes->get(RouteContext::REQUEST_ATTRIBUTE)[RouteContext::RESOURCE] // The filepath to your OpenAPI specification provided by the routing.
);
return JsonResponse::fromJsonString(
$serializer->serialize($pet, 'json', $serializationContext)
);
}
}
```
=> Add serialization context builder based on the OpenAPI specification for the Symfony Serializer

src/Serialization/SerializationContextBuilder.php, tests/Serialization/SerializationContextBuilderTest.php
This PR fixes an `Undefined property: stdClass::$type` error when a combined schema object created with `allOf` is referenced from another schema object.
=> Fix creating a serialization context when referencing a combined schema object

README.md, src/DependencyInjection/Configuration.php, src/DependencyInjection/NijensOpenapiExtension.php, src/Resources/config/services.xml, src/Routing/RouteLoader.php, tests/Functional/App/bundle.test.yaml, tests/Resources/specifications/route-loader-symfony-controller.json, tests/Routing/RouteLoaderTest.php
The PR ensures no code will break when existing bundle implementations use routes created by the `RouteLoader` in an `UrlGenerator`.
=> Add using the operationId as route name as optional feature to the RouteLoader

src/Json/Exception/InvalidArgumentException.php, src/Json/Reference.php, tests/Functional/App/openapi.yaml, tests/Functional/ExceptionHandling/ValidationResponsesTest.php, tests/Functional/ValidationResponsesTest.php, tests/Json/ReferenceTest.php
The `SchemaLoader`, besides loading the OpenAPI document, also handles dereferencing of the JSON schema [reference objects](https://spec.openapis.org/oas/v3.1.0#reference-object) (`$ref`) into `Nijens\OpenapiBundle\Json\Reference` instances. These reference instances should have allowed walking through the JSON schema without creating circular references within the deserialized JSON. Yet, the implementation lacked the actual walking through the JSON schema.
The external JSON schema validator library the bundle uses also didn't give a heads-up and ignored the reference instances. Therefore missing JSON schema constraints in the request body validation.
```yaml
requestBody:
application/json:
schema:
type: object
properties:
name:
type: string
category:
$ref: '#/components/schema/Category' …
```
=> Fix validation of constraints in reference objects within a JSON schema

composer.json, composer.lock, phpunit.xml.dist, src/Routing/RouteLoader.php
This PR deprecates the `x-symfony-controller` specification extension as it has been replaced with the `x-openapi-bundle` specification extension.
=> Deprecate x-symfony-controller specification extension

src/ExceptionHandling/EventSubscriber/ProblemExceptionToJsonResponseSubscriber.php, src/ExceptionHandling/EventSubscriber/ThrowableToProblemExceptionSubscriber.php
This change is necessary to fix transforming security exceptions to `ProblemException` instances.
Symfony's `ErrorListener` converts eg. an `AccessDeniedException` to an `AccessDeniedHttpException` even though the exception is already transformed to a `ProblemException` instance.
By changing the priority of the subscribers to execute after Symfony's `ErrorListener` the `AccessDeniedHttpException` (instead of the `AccessDeniedException`) is transformed to `ProblemException` instance and then successfully converted to a response.
=> Change priority of kernel exception subscribers to be able to process security exceptions

src/Deserialization/EventSubscriber/JsonRequestBodyDeserializationSubscriber.php, tests/Deserialization/EventSubscriber/JsonRequestBodyDeserializationSubscriberTest.php, tests/Functional/DeserializationTest.php
Fixes https://github.com/nijens/openapi-bundle/issues/88
=> Fixed subscriber priority

.github/workflows/continuous-integration.yaml, composer.json, composer.lock
Remove support for End-Of-Life Symfony versions in preparation for version 2.
=> Remove Symfony 4.4, 5.0, 5.1, 5.2 and 5.3 support

.github/workflows/continuous-integration.yaml, Makefile, composer.json, composer.lock, src/ExceptionHandling/Normalizer/AbstractProblemExceptionNormalizer.php, src/ExceptionHandling/Normalizer/ProblemExceptionNormalizer.php, src/ExceptionHandling/Normalizer/ProblemExceptionNormalizer.php8, tests/Deserialization/EventSubscriber/JsonRequestBodyDeserializationSubscriberTest.php, tests/Functional/ExceptionHandling/ErrorResponsesTest.php, tests/Validation/EventSubscriber/RequestValidationSubscriberTest.php
Adds Symfony 7 support to the `ProblemExceptionNormalizer` while maintaining backward compatibility with lower Symfony and PHP versions.
=> Add Symfony 7 support

src/Serialization/SerializationContextBuilder.php, src/Serialization/SerializationContextBuilderInterface.php, tests/Serialization/SerializationContextBuilderTest.php
Adds the possibility to add all the properties from the `anyOf` and `oneOf` union types to the serialization context. This has been added as an optional argument to ensure backward compatibility.
=> Add feature to treat anyOf and oneOf union types as allOf when creating a serialization context with the SerializationContextBuilder

src/Routing/RouteLoader.php, tests/Functional/App/openapi.yaml
Parts of the OpenAPI document are loaded as route attributes by the RouteLoader. The Symfony Router attempts to parse each attribute of a loaded route, checking for %-characters. When found, it tries to resolve them as service container parameters, throwing an exception if the parameter is not found.
This PR resolves the issue by preventing the resolution process, escaping %-characters by doubling them.
=> Prevent the Symfony Router from resolving %-characters in an OpenAPI document as service container parameters
